FROM python:3.11-slim

WORKDIR /frontend

COPY frontend/requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY frontend/ .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
